SFTP_HOST = "192.168.1.103"
SFTP_PORT = 22
SFTP_USER = "imove-pc"
SFTP_PASS = "ARAT"
SFTP_DIR = "/home/imove-pc/iMove"
MINIO_VZ_ACCESS = "admin"
MINIO_VZ_SECRET = "x>0.9;V59Ypp"
MINIO_VZ_ENDPOINT = "http://192.168.102.45:9000"
MINIO_VZ_BUCKET = "landingzone"
MINIO_HS_ACCESS = "admin"
MINIO_HS_SECRET = "x>0.9;V59Ypp"
MINIO_HS_ENDPOINT = "http://10.127.22.13:9001"
MINIO_HS_BUCKET = "landingzone"